#!/bin/bash

disks=${1}

# this script find all the partition and strip the out put as required

#!/bin/bash
# 1. populate the partitions with parted
# 2. extract only first two lines with head
# 3. combine first and second line with past and so on
# 4. filter out Disk workdir
# 5. filter out Model: word
# 6. replace /dev with :/dev so that we can get three column in QT

# make sure that previos file removed before writing new partitions.
if [ -f "/tmp/disks.txt" ]; then
	rm "/tmp/disks.txt"
fi

echo -e "$(parted -l | grep -E 'Model|dev' | paste -d " "  - - | sed 's/Disk//' | sed 's/Model://' | sed 's,/dev,:/dev,g')" 2>&1 >> "/tmp/disks.txt"

#echo -e "$(fdisk -l | grep -E 'Disk' | sed '/label/d' | sed '/identifier/d' | sed 's/Disk//')" 2>&1 >> "/tmp/disks.txt"


# make sure that previos file removed before writing new partitions.
if [ -f "/tmp/partitions.txt" ]; then
	rm "/tmp/partitions.txt"
fi

# 1. populate the partitions with fdisk
# 2. extract only lines by grep which starts with /dev
# 3. delete boot flage * from the bootable partition by using sed
# 4. delete the line containing Ext (extended partiion) by using sed
# 5. remove any USB drive which is shown by LBA
# 6. delete the blank spaces and and seperate each column with : by using tr command.
# 7. filter out any swap partition filesysstem
# 8. filter out any NTFS partition filesysstem

echo -e "$(fdisk -l ${disks} | grep ^/dev/ | sed 's/*//' | sed '/Ext/d' | sed '/LBA/d' | tr -s '[:blank:]' ':' | sed 's|Linux:swap:/:Solaris|swap|' | sed 's|HPFS/NTFS/exFAT|NTFS|')" >> "/tmp/partitions.txt"
