#!/bin/bash

# add items to favourites
#dconf write /org/gnome/shell/favorite-apps "['firefox.desktop', 'empathy.desktop', 'libreoffice-writer.desktop', 'nautilus.desktop', 'yelp.desktop']"

# show files on desktop
#gsettings set org.gnome.desktop.background show-desktop-icons true

# cleanup
sudo rm /usr/bin/adi
sudo rm /usr/bin/findpartition
sudo rm /usr/bin/livestart
sudo rm /usr/bin/copyfiles
sudo rm /usr/bin/adiscript
sudo rm /usr/share/applications/Installer.desktop
sudo rm -rf /usr/share/licenses/adi

sudo dracut '/boot/initramfs-linux.img'  $(uname -r) --force
sudo /usr/bin/grub-mkconfig -o /boot/grub/grub.cfg

sudo rm /etc/xdg/autostart/avouch-first-start.desktop
sudo rm /usr/bin/firststart


